### PR TITLE
Some documentation

### PR DESCRIPTION
**Pull request by JeffFessler**
Hopefully addresses #38 by showing all the docstrings via Documenter.

(This does not set up complete docs but hopefully will be a useful starting point.)

### CODE REVIEW

**Comment by JeffFessler** [comment]
@ivanslapnicar 
can you add a DOCUMENTER_KEY to this repo following the instructions here:
https://juliadocs.github.io/Documenter.jl/stable/lib/public/#DocumenterTools.genkeys
so that Documenter can deploy?
I do not have permissions to do that myself...

**Comment by JeffFessler** [comment]
@dlfivefifty are you able to add a DOCUMENTER_KEY to this repo?

**Comment by JeffFessler** [comment]
@dlfivefifty I see that you synced up the doc branch, thanks, but were you able to add a DOCUMENTER_KEY?
I can't directly see the presence or absence of that key from my view.  But it looks like it's not there because the pages didn't deploy:
https://juliamatrices.github.io/SpecialMatrices.jl/dev

And even thought github shows that "all checks have passed" the BuildAndDeploy part of the Documentation check shows that it failed to deploy:
https://github.com/JuliaMatrices/SpecialMatrices.jl/pull/45/checks?check_run_id=3451806955

**Comment by dlfivefifty** [comment]
Should be fixed now

**Pull request merged**
