### PR TITLE
Remove Toeplitz, Hankel, and circulant matrices

### PR DESCRIPTION
**Pull request by devmotion**
This fixes https://github.com/JuliaMatrices/SpecialMatrices.jl/issues/23.

With ToeplitzMatrices 0.7, the FFT-based factorization in ToeplitzMatrices is decoupled from the matrix type which is now as simple as the definitions in this package. Additionally, ToeplitzMatrices.jl has better support for these matrices and supports more operations besides multiplication.

I updated the README to point users to ToeplitzMatrices.

### CODE REVIEW

**Comment by JeffFessler** [comment]
Have you considered using `@deprecate` as an intermediate step rather than removing them abruptly?

**Comment by devmotion** [comment]
Yes, but I think it requires too much effort and probably one would still miss some breaking changes. It seemed one would have to add a dependency on ToeplitzMatrices, use `Base.@deprecate_binding` to deprecate the types, and use `@deprecate` for constructors (ToeplitzMatrices uses different constructors) and all other removed methods. And it would still be breaking if anyone actually works with the fields of the types since they have different names and e.g. in the case of `Toeplitz` SpecialMatrices just uses one vector whereas ToeplitzMatrices saves the first row and the first column separately.

**Review by JeffFessler — APPROVED** [review]

**Comment by JeffFessler** [comment]
@devmotion thanks for the detailed reply.  I agree that it sounds like it is not worth it.

@ivanslapnicar I have reviewed the changes and they look appropriate to me.
Do you want me to go ahead and approve them and work on tagging the new version?
Because it is such a major change I wanted to get your blessing first.

**Comment by JeffFessler** [comment]
@devmotion I agree that it would be preferable to put the link to Toeplitz Matrices near the top of the README because those types are probably the most commonly sought.

@ivanslapnicar Without any access, all I can do is offer suggestions...

**Comment by devmotion** [comment]
I updated the README.

**Comment by devmotion** [comment]
Bump :slightly_smiling_face:

**Comment by devmotion** [comment]
Bump :slightly_smiling_face:

**Comment by JeffFessler** [comment]
Because @ivanslapnicar gave the "go ahead" back in May, and now that v1.0.1 is safely tagged, I am going to go ahead and merge this PR.  It's had 3 sets of eyes on it so hopefully it's all OK!

**Comment by devmotion** [comment]
Great, thanks! Maybe you could tag a new release as well? The PR already updated the version number.

**Comment by JeffFessler** [comment]
Yep.  I had planned to do it earlier but was traveling in a region with no signal!

**Comment by devmotion** [comment]
No worries, thanks a lot!

**Pull request merged**
