### PR TITLE
Update CompatHelper.yml to v3

### PR DESCRIPTION
**Pull request by jishnub**

### CODE REVIEW

**Comment by jishnub** [comment]
I'm unsure why the documentation build fails to fetch the git repo

**Comment by JeffFessler** [comment]
Thanks for the PR.  I didn't realize that the recommended workflow has gotten so much longer:
https://github.com/JuliaRegistries/CompatHelper.jl/blob/master/.github/workflows/CompatHelper.yml
It looks like the DOCUMENTER_KEY is outdated.  I will try to fix that and then rerun the CI here.

**Comment by JeffFessler** [comment]
Actually I do not seem to have permission to update the key.
I can merge PRs but not manage the security.
@jishnub you seem to be a maintainer at the organization level here.
Can you update the security keys for this package?

**Comment by jishnub** [comment]
I don't have access to them either. Perhaps only the repo owner does.

**Comment by JeffFessler** [comment]
@ivanslapnicar I believe you are the owner of this repo, right?
Can you update the documenter key please?   There are instructions here:
https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Hosting-Documentation
To do this you need to go under "Settings."
Depending on your browser window size, you might not see the settings tab.  If you don't see it, then look for the "..." tab in the top right and it will be under that.

**Comment by JeffFessler** [comment]
@jishnub meanwhile I will go ahead and merge this PR.  Getting documenter to work again can be a separate issue.

**Comment by ivanslapnicar** [comment]
@JeffFessler, which "Settings" are you referring to?

**Comment by JeffFessler** [comment]
We refer to the Settings for the SpecialMatrices package that you own (I think).
It's the tab with the gear icon on the upper right if your window is wide enough:

Screen Shot 2022-10-17 at 9 00 44 PM

Under that tab is a "Security" section that has "Deploy keys" and "Secrets/actions" that apparently need updating (or installed, I can't tell) based on the CI logs.

**Comment by ivanslapnicar** [comment]
I don't have the Settings button. Does this mean that I might not be an owner anymore?
What do you suggest doing?

Screenshot 2022-10-18 at 17-23-25 JuliaMatrices_SpecialMatrices jl Julia package for working with special matrix types

**Comment by JeffFessler** [comment]
Screen Shot 2022-10-18 at 11 59 20 AM

**Comment by ivanslapnicar** [comment]
That is strange, indeed. Again, I am out of my depth there.
I just looked up and I found the message below from May 24, 2021.

I think that at that point I still had a Settings button and I assigned you as the owner since I did not know how to do the stuff needed.
Also, I could post to the repository and merge some pull requests.

Could you just make a pull request (a trivial one), just to see if I will be offered to merge it.

Best, Ivan



Error while trying to register: Register Failed
@JeffFessler<https://github.com/JeffFessler>, it looks like you are not a publicly listed member/owner in the parent organization (JuliaMatrices).
If you are a member/owner, you will need to change your membership to public. See GitHub Help<https://help.github.com/en/articles/publicizing-or-hiding-organization-membership>


Prof. dr. sc. Ivan Slapničar
Sveučilište u Splitu / University of Split
FESB
R. Boškovića 32
HR-21000 Split
Hrvatska / Croatia
Phone: + 385 21 305893
Ured/Office: B803
________________________________
Šalje: Jeff Fessler ***@***.***>
Poslano: 18. listopada 2022. 17:58
Prima: JuliaMatrices/SpecialMatrices.jl ***@***.***>
Kopija: Ivan Slapničar ***@***.***>; Mention ***@***.***>
Predmet: Re: [JuliaMatrices/SpecialMatrices.jl] Update CompatHelper.yml to v3 (PR #56)


BTW, I have a "Settings" button for this repo, but under that button I do not have access to the ssh keys, whereas for repos that I own I can set/delete/update those keys.

**Comment by jishnub** [comment]
I think anyone who is a member of the organization can merge PRs, so that might not reveal the owner

**Comment by JeffFessler** [comment]
@ivanslapnicar there are already a few PRs in the queue.  none of them should be merged (they all need work) but you can see if you have the "squash and merge" button available on on the non-draft ones.  i'm pretty sure you will, like i do.

**Comment by JeffFessler** [comment]
I checked and I am an "outside collaborator on 1 repository" for JuliaMatrices.
@ivanslapnicar you can try this link to check your status:
https://github.com/settings/organizations

**Comment by ivanslapnicar** [comment]
Yes, I have the "Merge the pull request" button, and I can choose the
"Squash and merge", too.


________________________________
Šalje: Jeff Fessler ***@***.***>
Poslano: 18. listopada 2022. 19:54
Prima: JuliaMatrices/SpecialMatrices.jl ***@***.***>
Kopija: Ivan Slapničar ***@***.***>; Mention ***@***.***>
Predmet: Re: [JuliaMatrices/SpecialMatrices.jl] Update CompatHelper.yml to v3 (PR #56)


@ivanslapnicar<https://github.com/ivanslapnicar> there are already a few PRs in the queue. none of them should be merged (they all need work) but you can see if you have the "squash and merge" button available on on the non-draft ones. i'm pretty sure you will, like i do.

**Comment by jishnub** [comment]
I think "outside collaborator on 1 repository" implies that one is a member of a repo while not being a member of the organization that the repo belongs to.

**Comment by JeffFessler** [comment]
@dkarrasch  Are you an owner of this package?  If so, can you set up DOCUMENTER_KEY for it?
If not, can you help us find the owner?  I thought everyone at the org level would be an owner, but it seems not because @jishnub is there at org level but says he is not an owner.  How do we figure out who has access to the ssh key setup?

**Comment by jishnub** [comment]
Incidentally, are we sure that `DOCUMENTER_KEY` is the issue? When I look at previous `Documenter` runs at https://github.com/JuliaMatrices/SpecialMatrices.jl/actions/workflows/Documentation.yml, I see that there was a successful run 3 months back. Assuming that the secrets haven't changed in a few months, the variable should be properly set up, and the error message suggestion may not be the real cause.

**Comment by dkarrasch** [comment]
@JeffFessler I don't even have a settings button, but merge rights.

**Comment by ararslan** [comment]
There was a `DOCUMENTER_KEY` repository secret but no associated deploy key. I've updated both. I'll also update folks' permissions to increase the bus factor here.

**Comment by ivanslapnicar** [comment]
Thanks a million!

Prof. dr. sc. Ivan Slapničar
Sveučilište u Splitu / University of Split
FESB
R. Boškovića 32
HR-21000 Split
Hrvatska / Croatia
Phone: + 385 21 305893
Ured/Office: B803
________________________________
Šalje: Alex Arslan ***@***.***>
Poslano: 20. listopada 2022. 18:21
Prima: JuliaMatrices/SpecialMatrices.jl ***@***.***>
Kopija: Ivan Slapničar ***@***.***>; Mention ***@***.***>
Predmet: Re: [JuliaMatrices/SpecialMatrices.jl] Update CompatHelper.yml to v3 (PR #56)


There was a DOCUMENTER_KEY repository secret but no associated deploy key. I've updated both. I'll also update folks' permissions to increase the bus factor here.

**Pull request merged**
